# Generated by Django 5.2.6 on 2025-09-03 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.CharField(choices=[('filhote', 'Filhote'), ('jovem', 'Jovem'), ('adulto', 'Adulto'), ('idoso', 'Idoso')], max_length=10, verbose_name='Faixa etária')),
                ('raca', models.CharField(max_length=50, verbose_name='Raça')),
                ('porte', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=10, verbose_name='Porte')),
                ('temperamento', models.CharField(choices=[('calmo', 'Calmo'), ('ativo', 'Ativo'), ('tímido', 'Tímido'), ('brincalhão', 'Brincalhão')], max_length=20, verbose_name='Temperamento')),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da doação')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data da doação')),
                ('forma_pagamento', models.CharField(choices=[('pix', 'PIX'), ('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência')], max_length=20, verbose_name='Forma de pagamento')),
                ('nome_doador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do doador')),
            ],
            options={
                'verbose_name': 'Doação',
                'verbose_name_plural': 'Doações',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do animal')),
                ('imagem', models.ImageField(upload_to='animais/', verbose_name='Imagem do animal')),
                ('caracteristica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.caracteristica', verbose_name='Características')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do solicitante')),
                ('motivo_adocao', models.TextField(verbose_name='Motivo para adoção')),
                ('disponibilidade', models.TextField(verbose_name='Disponibilidade (tempo, espaço etc.)')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da solicitação')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animal', verbose_name='Animal')),
            ],
            options={
                'verbose_name': 'Formulário de Adoção',
                'verbose_name_plural': 'Formulários de Adoção',
            },
        ),
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmacao', models.BooleanField(default=False, verbose_name='Confirmação da adoção')),
                ('data_adocao', models.DateField(auto_now_add=True, verbose_name='Data da adoção')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animal', verbose_name='Animal adotado')),
                ('formulario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.formulario', verbose_name='Formulário vinculado')),
            ],
            options={
                'verbose_name': 'Adoção',
                'verbose_name_plural': 'Adoções',
            },
        ),
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da história')),
                ('descricao', models.TextField(verbose_name='Descrição da história')),
                ('envolvidos', models.TextField(blank=True, null=True, verbose_name='Envolvidos no projeto')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('adocao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.adocao', verbose_name='Adoção relacionada')),
                ('animais', models.ManyToManyField(blank=True, to='app.animal', verbose_name='Animais envolvidos')),
            ],
            options={
                'verbose_name': 'História',
                'verbose_name_plural': 'Histórias',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da pessoa')),
                ('idade', models.PositiveIntegerField(verbose_name='Idade')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.AddField(
            model_name='formulario',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa'),
        ),
        migrations.AddField(
            model_name='adocao',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Adotante'),
        ),
    ]
