# Generated by Django 5.2.6 on 2025-09-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
    ]
